version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "ghcr.io/fuabioo/basket:{{ .Version }}-amd64"
      - "ghcr.io/fuabioo/basket:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/Fuabioo/basket"
      - "--label=org.opencontainers.image.description=Simple file server"
      - "--platform=linux/amd64"
    goarch: amd64
    extra_files:
      - assets/
  - image_templates:
      - "ghcr.io/fuabioo/basket:{{ .Version }}-arm64"
      - "ghcr.io/fuabioo/basket:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/Fuabioo/basket"
      - "--label=org.opencontainers.image.description=Simple file server"
      - "--platform=linux/arm64"
    goarch: arm64
    extra_files:
      - assets/
  - image_templates:
      - "ghcr.io/fuabioo/basket:{{ .Version }}-armv6"
      - "ghcr.io/fuabioo/basket:latest-armv6"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/Fuabioo/basket"
      - "--label=org.opencontainers.image.description=Simple file server"
      - "--platform=linux/arm/v6"
    goarch: arm
    goarm: 6
    extra_files:
      - assets/
  - image_templates:
      - "ghcr.io/fuabioo/basket:{{ .Version }}-armv7"
      - "ghcr.io/fuabioo/basket:latest-armv7"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/Fuabioo/basket"
      - "--label=org.opencontainers.image.description=Simple file server"
      - "--platform=linux/arm/v7"
    goarch: arm
    goarm: 7
    extra_files:
      - assets/

docker_manifests:
  - name_template: ghcr.io/fuabioo/basket:{{ .Version }}
    image_templates:
      - ghcr.io/fuabioo/basket:{{ .Version }}-amd64
      - ghcr.io/fuabioo/basket:{{ .Version }}-arm64
      - ghcr.io/fuabioo/basket:{{ .Version }}-armv6
      - ghcr.io/fuabioo/basket:{{ .Version }}-armv7
  - name_template: ghcr.io/fuabioo/basket:latest
    image_templates:
      - ghcr.io/fuabioo/basket:latest-amd64
      - ghcr.io/fuabioo/basket:latest-arm64
      - ghcr.io/fuabioo/basket:latest-armv6
      - ghcr.io/fuabioo/basket:latest-armv7

release:
  github:
    owner: Fuabioo
    name: basket
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "README"
      - Merge pull request
      - Merge branch
